app = "xboom-bot"

[env]
PORT = "10000"

[[services]]
  internal_port = 10000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["http"]
    port = 443
