
# render.yaml - version safe pour repo public
services:
  - type: web
    name: 1xboom-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    autoDeploy: true
    healthCheckPath: "/ping"
    envVars:
      - key: BOT_TOKEN
        fromEnvVar: BOT_TOKEN      # valeur configurée sur Render
      - key: SUPABASE_URL
        fromEnvVar: SUPABASE_URL   # valeur configurée sur Render
      - key: SUPABASE_KEY
        fromEnvVar: SUPABASE_KEY   # valeur configurée sur Render
      - key: ADMIN_ID
        fromEnvVar: ADMIN_ID       # valeur configurée sur Render
      - key: TZ
        fromEnvVar: TZ     
